version: '3.8'

services:
  db:
    image: postgres
    container_name: pibot-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${PI_BOT_DB_USER}
      POSTGRES_PASSWORD: ${PI_BOT_DB_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
  pibot:
    # HOT RELOAD
    #    build:
    #      context: .
    #      dockerfile: hr.Dockerfile
    #    volumes:
    #        - ./:/app

    build: .
    image: majorro/pibot
    container_name: pibot
    restart: always
    environment:
      - PI_BOT_TOKEN=${PI_BOT_TOKEN}
      - PI_BOT_DB_HOST=${PI_BOT_DB_HOST}
      - PI_BOT_DB_PORT=${PI_BOT_DB_PORT}
      - PI_BOT_DB_USER=${PI_BOT_DB_USER}
      - PI_BOT_DB_PASSWORD=${PI_BOT_DB_PASSWORD}
    depends_on:
      - db

volumes:
  db-data:
