version: '3.8'

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  pibot:
    build: .
    # noinspection ComposeUnknownValues
    restart: on-failure:5 # TODO: always?
    environment:
      - PI_BOT_TOKEN=6424847260:AAG1YdfFDh_vfZNnCi0U5Qpe4c1WodCTliA
    depends_on:
      - db
